#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../default.css" />
#+OPTIONS: toc:nil
#+OPTIONS: num:nil

* List of Workshop Papers

- 1. *松井 大樹*, 萩原 涼, 大崎 博之, "拠点間 DTN ルーティングにおける
  メッセージ配送遅延に関する 一検討," 電子情報通信学会 ソサイエティ大
  会 講演論文集(B-16-4), p. 355, Sept. 2016.

- 2. *D. Matsui*, R. Hagihara, Y. Yamasaki, and H. Ohsaki, "Deriving
  the average message delivery delay in geographic DTN routing,"
  Technical Report of IEICE (IA2016-31), pp. 27-32, Nov. 2016.
-----
- 3. *D. Matsui*, R. Hagihara, Y. Yamasaki, and H. Ohsaki, "Deriving
  the average message delivery delay in geographic DTN routing under
  random walk mobility model," 電子情報通信学会 総合大会 講演論文集
  (BS-1-29), pp. 56-57, Mar. 2017.

- 4. *松井 大樹*, 西川 純由, 山崎 康広, 大崎 博之, "大規模ネットワーク
  における複製型拠点間 DTN ルーティングの特性解析に関する一検討," 電子
  情報通信学会 ソサイエティ大会 講演論文集(B-16-6), Sept. 2017.

- 5. 西川純由, *松井大樹*, 山崎 康広, 大崎 博之, "大規模ネットワークに
  おける拠点間 DTN ルーティングのメッセージ配送遅延に関する一検討," 電
  子情報通信学会 ソサイエティ大会 講演論文集(BS-3-2), pp. S-5,
  Sept. 2017.

- 6. S. Nishikawa, *D. Matsui*, Y. Yamasaki, and H. Ohsaki,
  "Approximate analysis of message delivery delay in large-scale
  geographic DTN routing," Technical Report of IEICE (IA2017-11),
  pp. 105-108, Nov. 2017.
-----
- 7. 阪口 亮太, *松井 大樹*, 中村 遼, 山崎 康広, 大崎 博之, "グラフ上
  の移動モデルの違いが初回到着時間に与える影響に関する一検討," 電子情
  報通信学会 ソサイエティ大会 講演論文集 (B-16-12), Sept. 2018.

- 8. 前川 龍一郎, *松井 大樹*, 山崎 康広, 大崎 博之, "Pi 制御器を用い
  たIEEE 1588-2008 時刻同期プロトコルの安定性に関する一検討," 電子情報
  通信学会 ソサイエティ大会 講演論文集 (B-16-15), Sept. 2018.

- 9. *松井 大樹*, 大崎 博之, "グラフ上の制約付きランダムウェイポイント
  移動モデルの特性に関する一検討," 電子情報通信学会 ソサイエティ大会講
  演論文集(B-16-10, Sept. 2018.
-----
- 10. 前川 龍一郎, *松井 大樹*, 山崎 康広, 大崎 博之, "Pi 制御器を用い
  たIEEE 1588-2008 時刻同期機構のモデル化," 電子情報通信学会技術研究報
  告(IA2019-XX), p. XXX, Jan. 2019.

- 11. 前川 龍一郎, *松井 大樹*, 山崎 康広, 大崎 博之, "Pi 制御器を用い
  たIEEE 1588-2008 時刻同期プロトコルの安定性解析に関する一検討," 電子
  情報通信学会 総合大会 講演論文集 (B-11), p. XXX, Mar. 2019.

- 12. 阪口 亮太, *松井 大樹*, 中村 遼, 山崎 康広, 大崎 博之, "グラフ上
  のランダムウォークにおける遷移確率の偏りが移動特性に 与える影響に関
  する一考察," 電子情報通信学会 総合大会 講演論文集 (BS-7-9),
  pp. S-159, Mar. 2019.

- 13. 中村 遼, 阪口 亮太, 山下 量之, *松井 大樹*, 大崎 博之, "ネットワー
  クトポロジが情報探索・配送・拡散に与える影響," 電子情報通信学会技術
  研究報告 (PN2019-4), vol. 119, pp. 17-24, Apr. 2019.
