export const SITE = {
  website: "https://d-matsui.github.io/",
  author: "Daiki Matsui",
  profile: "https://github.com/d-matsui",
  desc: "Personal blog about software engineering, AI, and learning journey.",
  title: "Daiki Matsui",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/d-matsui/d-matsui.github.io/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "ja",
  timezone: "Asia/Tokyo",
} as const;
